version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - bug
    cooldown:
      default-days: 30
      exclude:
        - "brownserve-uk/*"
    groups:
      brownserve:
        patterns:
          - "brownserve-uk/*"
    exclude-paths:
      - ".github/workflows/vc-stub-a.yaml"
      - ".github/workflows/vc-glob-*.yaml"

  # vb: template source variants
  - package-ecosystem: github-actions
    directory: /vb/plain/.github/workflows
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /vb/rootstyle
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /vb/jinja-suffix/.github/workflows
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /vb/jinja-blocks/.github/workflows
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /vb/jinja-comments/.github/workflows
    schedule:
      interval: daily

  # vd: dev container variants
  - package-ecosystem: devcontainers
    directory: /vb/devc-plain
    schedule:
      interval: daily
  - package-ecosystem: devcontainers
    directory: /vb/devc-jinja
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /vb/devc-plain/.devcontainer
    schedule:
      interval: daily
