name: builds
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: Brownserve-UK/copier-scratch/.github/workflows/build.yaml@v1.1.0

  action:
    runs-on: ubuntu-latest
    steps:
      - uses: Brownserve-UK/copier-scratch@v1.1.0
