name: e11-skipped
on: workflow_dispatch

jobs:
  release:
    permissions:
      contents: read
    uses: Brownserve-UK/copier-scratch/.github/workflows/release.yaml@v1.1.0
    with:
      container: false
