name: e11-denied
on: workflow_dispatch

jobs:
  release:
    permissions:
      contents: read
    uses: Brownserve-UK/copier-scratch/.github/workflows/release.yaml@v1.0.0
    with:
      container: true
